# Generated by Django 3.1.7 on 2021-02-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vtuber',
        ),
    ]
