# Generated by Django 3.1.7 on 2021-02-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vtuber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtuber',
            name='id',
        ),
        migrations.AlterField(
            model_name='vtuber',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
