# Generated by Django 3.1.7 on 2021-02-25 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 4, 33, 53, 651839, tzinfo=utc)),
        ),
    ]
